name: Lighthouse CI

on: [push]

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Start a local server
        run: |
          npm install -g serve
          serve -s . &
          echo $! > server.pid

      - name: Run Lighthouse CI
        run: npx lhci autorun
        env:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.ref_name }}

      - name: Stop the local server
        run: kill $(cat server.pid) || true
